import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1769984330494 implements MigrationInterface {
    name = 'InitialSchema1769984330494'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."sponsors_status_enum" AS ENUM('pending', 'approved', 'rejected', 'disabled')`);
        await queryRunner.query(`CREATE TABLE "sponsors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "business_name" character varying(255) NOT NULL, "description" text, "category" character varying(100), "logo_url" character varying(500), "contact_email" character varying(255) NOT NULL, "status" "public"."sponsors_status_enum" NOT NULL DEFAULT 'pending', "reviewed_by" uuid, "reviewed_at" TIMESTAMP, "rejection_reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fbc6d68d34dd7eab444f72b8f24" UNIQUE ("user_id"), CONSTRAINT "PK_6d1114fe7e65855154351b66bfc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sponsor_enrollments_status_enum" AS ENUM('active', 'inactive', 'completed')`);
        await queryRunner.query(`CREATE TABLE "sponsor_enrollments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sponsored_goal_id" uuid NOT NULL, "user_id" uuid NOT NULL, "status" "public"."sponsor_enrollments_status_enum" NOT NULL DEFAULT 'active', "enrolled_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9ddcaf3af0876fd468720847583" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9bd1fcb0298e877cd050f3e2eb" ON "sponsor_enrollments" ("sponsored_goal_id", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."projects_status_enum" AS ENUM('pending', 'in_progress', 'completed')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, "purpose" text, "budget" numeric, "final_date" date, "resources_available" jsonb, "resources_needed" jsonb, "sponsored_goal_id" uuid, "enrollment_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "status" "public"."projects_status_enum" NOT NULL DEFAULT 'pending', "reward_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sponsored_goals_verification_method_enum" AS ENUM('qr', 'checklist', 'manual', 'external_api')`);
        await queryRunner.query(`CREATE TABLE "sponsored_goals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sponsor_id" uuid NOT NULL, "project_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, "start_date" date NOT NULL, "end_date" date NOT NULL, "verification_method" "public"."sponsored_goals_verification_method_enum" NOT NULL, "reward_id" uuid, "max_users" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ecebf4843a11994010bbb125443" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "category_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bfff3649c69b4d58dd0e7e1d35d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_802a1731c44150d3e7e30ea75c" ON "user_categories" ("user_id", "category_id") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'sponsor', 'admin')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "firebase_uid" character varying(255) NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_0fd54ced5cc75f7cb92925dd803" UNIQUE ("firebase_uid"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."milestones_status_enum" AS ENUM('pending', 'in_progress', 'completed')`);
        await queryRunner.query(`CREATE TABLE "milestones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, "status" "public"."milestones_status_enum" NOT NULL DEFAULT 'pending', "reward_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0bdbfe399c777a6a8520ff902d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprints" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "milestone_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text, "acceptance_criteria" jsonb, "start_date" date NOT NULL, "end_date" date NOT NULL, "resources_available" jsonb, "resources_needed" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6800aa2e0f508561812c4b9afb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('pending', 'in_progress', 'completed')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "milestone_id" uuid NOT NULL, "sprint_id" uuid, "name" character varying(255) NOT NULL, "description" text, "status" "public"."tasks_status_enum" NOT NULL DEFAULT 'pending', "start_date" date NOT NULL, "end_date" date NOT NULL, "resources_available" jsonb, "resources_needed" jsonb, "incentive_points" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "checklist_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid, "sponsored_goal_id" uuid, "description" text NOT NULL, "is_required" boolean NOT NULL DEFAULT false, "is_checked" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bae00945a1d4789bd648e583e29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."verification_events_method_enum" AS ENUM('qr', 'checklist', 'manual', 'external_api')`);
        await queryRunner.query(`CREATE TABLE "verification_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "enrollment_id" uuid NOT NULL, "sponsored_goal_id" uuid NOT NULL, "method" "public"."verification_events_method_enum" NOT NULL, "data" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_98547c645e27a46999519b11e6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sprint_id" uuid NOT NULL, "user_id" uuid NOT NULL, "progress_percentage" integer NOT NULL, "extra_points" integer NOT NULL DEFAULT '0', "summary" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a58846cda7809a04eb1af8bc9bc" UNIQUE ("sprint_id"), CONSTRAINT "REL_a58846cda7809a04eb1af8bc9b" UNIQUE ("sprint_id"), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "retrospectives" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sprint_id" uuid NOT NULL, "user_id" uuid NOT NULL, "what_went_well" text NOT NULL, "what_went_wrong" text NOT NULL, "improvements" text, "is_public" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1bf0d2fa606f1e04d8bf1ce2bc8" UNIQUE ("sprint_id"), CONSTRAINT "REL_1bf0d2fa606f1e04d8bf1ce2bc" UNIQUE ("sprint_id"), CONSTRAINT "PK_bb2dfd48493b3906269b2de23c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rewards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sponsor_id" uuid, "name" character varying(255) NOT NULL, "description" text, "claim_instructions" text, "claim_link" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3d947441a48debeb9b7366f8b8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_rewards_status_enum" AS ENUM('pending', 'claimed', 'delivered')`);
        await queryRunner.query(`CREATE TABLE "user_rewards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "reward_id" uuid NOT NULL, "status" "public"."user_rewards_status_enum" NOT NULL DEFAULT 'pending', "claimed_at" TIMESTAMP, "delivered_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_86078010f64a891601beef7c54f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5a77582dd360cb3d5ba86b3642" ON "user_rewards" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "badges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "icon_url" character varying(500), "required_points" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8a651318b8de577e8e217676466" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_badges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "badge_id" uuid NOT NULL, "earned_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0ca139216824d745a930065706a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_201b6e34825dc5bd06181320bd" ON "user_badges" ("user_id", "badge_id") `);
        await queryRunner.query(`CREATE TABLE "points_wallet" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "balance" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_790ed25284251ac04cb25bb9613" UNIQUE ("user_id"), CONSTRAINT "REL_790ed25284251ac04cb25bb961" UNIQUE ("user_id"), CONSTRAINT "PK_e5075df2605e5ae52bc2f7b9290" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."points_transactions_source_type_enum" AS ENUM('task', 'daily', 'sponsored_goal', 'review', 'badge')`);
        await queryRunner.query(`CREATE TABLE "points_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "change" integer NOT NULL, "reason" text NOT NULL, "source_type" "public"."points_transactions_source_type_enum" NOT NULL, "source_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b368729603fe6bc50fdb6750b33" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_93fcf719236faeab6d7fc0d0cf" ON "points_transactions" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."daily_entries_difficulty_enum" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`CREATE TYPE "public"."daily_entries_energy_change_enum" AS ENUM('increased', 'stable', 'decreased')`);
        await queryRunner.query(`CREATE TABLE "daily_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "task_id" uuid, "sprint_id" uuid NOT NULL, "notes_yesterday" text NOT NULL, "notes_today" text NOT NULL, "difficulty" "public"."daily_entries_difficulty_enum" NOT NULL, "energy_change" "public"."daily_entries_energy_change_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_028b8ddda254a474018429f3c81" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sponsored_goal_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sponsored_goal_id" uuid NOT NULL, "category_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_baf428deab3cd8a6e73f94852c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8f73aa4577d90f86723e254ce3" ON "sponsored_goal_categories" ("sponsored_goal_id", "category_id") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "action" character varying(255) NOT NULL, "entity" character varying(255) NOT NULL, "entity_id" character varying(255) NOT NULL, "previous_data" jsonb, "new_data" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_82edbc5f8a1821ff01b8b9c865" ON "audit_logs" ("entity", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2f68e345c05e8166ff9deea1ab" ON "audit_logs" ("user_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "sponsors" ADD CONSTRAINT "FK_fbc6d68d34dd7eab444f72b8f24" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsors" ADD CONSTRAINT "FK_56883b474a6fd2813f19865435f" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsor_enrollments" ADD CONSTRAINT "FK_46e6632237c3779570597e08798" FOREIGN KEY ("sponsored_goal_id") REFERENCES "sponsored_goals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsor_enrollments" ADD CONSTRAINT "FK_ee237474d5d61b55ed2342818f9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_bd55b203eb9f92b0c8390380010" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_3073fe31e715a5c1d8c2b00772e" FOREIGN KEY ("sponsored_goal_id") REFERENCES "sponsored_goals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_0139e91ca09d5d6562536e62a9e" FOREIGN KEY ("enrollment_id") REFERENCES "sponsor_enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsored_goals" ADD CONSTRAINT "FK_e8f5238dc4ba3541bb7a9577c65" FOREIGN KEY ("sponsor_id") REFERENCES "sponsors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsored_goals" ADD CONSTRAINT "FK_159bc28dae81d1fe812b836012e" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_categories" ADD CONSTRAINT "FK_45435150cf9c026d714c9d847e6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_categories" ADD CONSTRAINT "FK_78d822ee1ebeb703dbecdf8e616" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "milestones" ADD CONSTRAINT "FK_2204463ea4c5c1872e1fb2b8ffb" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_548e747b7a3746904a5cd444dad" FOREIGN KEY ("milestone_id") REFERENCES "milestones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_39abeb50240a7312a00786c9b24" FOREIGN KEY ("milestone_id") REFERENCES "milestones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_b512d5a489d692f66569978b8a7" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checklist_items" ADD CONSTRAINT "FK_ddce58fe3b634074f0eb8168d43" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_events" ADD CONSTRAINT "FK_ed3e24044602495e20fdf7c349a" FOREIGN KEY ("enrollment_id") REFERENCES "sponsor_enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_events" ADD CONSTRAINT "FK_8c93a9e8a52a87659258cc1ead7" FOREIGN KEY ("sponsored_goal_id") REFERENCES "sponsored_goals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_a58846cda7809a04eb1af8bc9bc" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retrospectives" ADD CONSTRAINT "FK_1bf0d2fa606f1e04d8bf1ce2bc8" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retrospectives" ADD CONSTRAINT "FK_2b19f37cb3a404f9e5b80027d6f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rewards" ADD CONSTRAINT "FK_504e429bee8dbbfbbdbec81888a" FOREIGN KEY ("sponsor_id") REFERENCES "sponsors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_rewards" ADD CONSTRAINT "FK_cc6556a0f2fe56932c9187240de" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_rewards" ADD CONSTRAINT "FK_2407370386f8e7e2e41cdecef55" FOREIGN KEY ("reward_id") REFERENCES "rewards"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_badges" ADD CONSTRAINT "FK_f1221d9b1aaa64b1f3c98ed46d3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_badges" ADD CONSTRAINT "FK_715b81e610ab276ff6603cfc8e8" FOREIGN KEY ("badge_id") REFERENCES "badges"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "points_wallet" ADD CONSTRAINT "FK_790ed25284251ac04cb25bb9613" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "points_transactions" ADD CONSTRAINT "FK_c727fda76a7af7e135d74721a76" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_entries" ADD CONSTRAINT "FK_4b43f27ebac9da6efb861963a9d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_entries" ADD CONSTRAINT "FK_0d60e3bf0464cc5d426fa32b835" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_entries" ADD CONSTRAINT "FK_e795087516c6ab447f991e03ca5" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsored_goal_categories" ADD CONSTRAINT "FK_86cb30141214da8f7bb51764d44" FOREIGN KEY ("sponsored_goal_id") REFERENCES "sponsored_goals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sponsored_goal_categories" ADD CONSTRAINT "FK_4539e0157d030be57d48ddceaf9" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "sponsored_goal_categories" DROP CONSTRAINT "FK_4539e0157d030be57d48ddceaf9"`);
        await queryRunner.query(`ALTER TABLE "sponsored_goal_categories" DROP CONSTRAINT "FK_86cb30141214da8f7bb51764d44"`);
        await queryRunner.query(`ALTER TABLE "daily_entries" DROP CONSTRAINT "FK_e795087516c6ab447f991e03ca5"`);
        await queryRunner.query(`ALTER TABLE "daily_entries" DROP CONSTRAINT "FK_0d60e3bf0464cc5d426fa32b835"`);
        await queryRunner.query(`ALTER TABLE "daily_entries" DROP CONSTRAINT "FK_4b43f27ebac9da6efb861963a9d"`);
        await queryRunner.query(`ALTER TABLE "points_transactions" DROP CONSTRAINT "FK_c727fda76a7af7e135d74721a76"`);
        await queryRunner.query(`ALTER TABLE "points_wallet" DROP CONSTRAINT "FK_790ed25284251ac04cb25bb9613"`);
        await queryRunner.query(`ALTER TABLE "user_badges" DROP CONSTRAINT "FK_715b81e610ab276ff6603cfc8e8"`);
        await queryRunner.query(`ALTER TABLE "user_badges" DROP CONSTRAINT "FK_f1221d9b1aaa64b1f3c98ed46d3"`);
        await queryRunner.query(`ALTER TABLE "user_rewards" DROP CONSTRAINT "FK_2407370386f8e7e2e41cdecef55"`);
        await queryRunner.query(`ALTER TABLE "user_rewards" DROP CONSTRAINT "FK_cc6556a0f2fe56932c9187240de"`);
        await queryRunner.query(`ALTER TABLE "rewards" DROP CONSTRAINT "FK_504e429bee8dbbfbbdbec81888a"`);
        await queryRunner.query(`ALTER TABLE "retrospectives" DROP CONSTRAINT "FK_2b19f37cb3a404f9e5b80027d6f"`);
        await queryRunner.query(`ALTER TABLE "retrospectives" DROP CONSTRAINT "FK_1bf0d2fa606f1e04d8bf1ce2bc8"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_a58846cda7809a04eb1af8bc9bc"`);
        await queryRunner.query(`ALTER TABLE "verification_events" DROP CONSTRAINT "FK_8c93a9e8a52a87659258cc1ead7"`);
        await queryRunner.query(`ALTER TABLE "verification_events" DROP CONSTRAINT "FK_ed3e24044602495e20fdf7c349a"`);
        await queryRunner.query(`ALTER TABLE "checklist_items" DROP CONSTRAINT "FK_ddce58fe3b634074f0eb8168d43"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_b512d5a489d692f66569978b8a7"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_39abeb50240a7312a00786c9b24"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_548e747b7a3746904a5cd444dad"`);
        await queryRunner.query(`ALTER TABLE "milestones" DROP CONSTRAINT "FK_2204463ea4c5c1872e1fb2b8ffb"`);
        await queryRunner.query(`ALTER TABLE "user_categories" DROP CONSTRAINT "FK_78d822ee1ebeb703dbecdf8e616"`);
        await queryRunner.query(`ALTER TABLE "user_categories" DROP CONSTRAINT "FK_45435150cf9c026d714c9d847e6"`);
        await queryRunner.query(`ALTER TABLE "sponsored_goals" DROP CONSTRAINT "FK_159bc28dae81d1fe812b836012e"`);
        await queryRunner.query(`ALTER TABLE "sponsored_goals" DROP CONSTRAINT "FK_e8f5238dc4ba3541bb7a9577c65"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_0139e91ca09d5d6562536e62a9e"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_3073fe31e715a5c1d8c2b00772e"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_bd55b203eb9f92b0c8390380010"`);
        await queryRunner.query(`ALTER TABLE "sponsor_enrollments" DROP CONSTRAINT "FK_ee237474d5d61b55ed2342818f9"`);
        await queryRunner.query(`ALTER TABLE "sponsor_enrollments" DROP CONSTRAINT "FK_46e6632237c3779570597e08798"`);
        await queryRunner.query(`ALTER TABLE "sponsors" DROP CONSTRAINT "FK_56883b474a6fd2813f19865435f"`);
        await queryRunner.query(`ALTER TABLE "sponsors" DROP CONSTRAINT "FK_fbc6d68d34dd7eab444f72b8f24"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f68e345c05e8166ff9deea1ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82edbc5f8a1821ff01b8b9c865"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f73aa4577d90f86723e254ce3"`);
        await queryRunner.query(`DROP TABLE "sponsored_goal_categories"`);
        await queryRunner.query(`DROP TABLE "daily_entries"`);
        await queryRunner.query(`DROP TYPE "public"."daily_entries_energy_change_enum"`);
        await queryRunner.query(`DROP TYPE "public"."daily_entries_difficulty_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93fcf719236faeab6d7fc0d0cf"`);
        await queryRunner.query(`DROP TABLE "points_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."points_transactions_source_type_enum"`);
        await queryRunner.query(`DROP TABLE "points_wallet"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_201b6e34825dc5bd06181320bd"`);
        await queryRunner.query(`DROP TABLE "user_badges"`);
        await queryRunner.query(`DROP TABLE "badges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a77582dd360cb3d5ba86b3642"`);
        await queryRunner.query(`DROP TABLE "user_rewards"`);
        await queryRunner.query(`DROP TYPE "public"."user_rewards_status_enum"`);
        await queryRunner.query(`DROP TABLE "rewards"`);
        await queryRunner.query(`DROP TABLE "retrospectives"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TABLE "verification_events"`);
        await queryRunner.query(`DROP TYPE "public"."verification_events_method_enum"`);
        await queryRunner.query(`DROP TABLE "checklist_items"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
        await queryRunner.query(`DROP TABLE "sprints"`);
        await queryRunner.query(`DROP TABLE "milestones"`);
        await queryRunner.query(`DROP TYPE "public"."milestones_status_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_802a1731c44150d3e7e30ea75c"`);
        await queryRunner.query(`DROP TABLE "user_categories"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "sponsored_goals"`);
        await queryRunner.query(`DROP TYPE "public"."sponsored_goals_verification_method_enum"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."projects_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9bd1fcb0298e877cd050f3e2eb"`);
        await queryRunner.query(`DROP TABLE "sponsor_enrollments"`);
        await queryRunner.query(`DROP TYPE "public"."sponsor_enrollments_status_enum"`);
        await queryRunner.query(`DROP TABLE "sponsors"`);
        await queryRunner.query(`DROP TYPE "public"."sponsors_status_enum"`);
    }

}
